[package]
name = "pulsar_stellar"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18.0", features = ["extension-module"] }
nalgebra = "0.31"  # Linear algebra for robotics
serde = { version = "1.0", features = ["derive"] }
